### ISSUE TITLE
怎么用啊，有没有文档？

### ISSUE THREAD

**Issue by amangqq** [abilian/flask-vite#1]
* Flask-Tailwind version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by amangqq** [comment]
Can you give me an example?

**Comment by sfermigier** [comment]
I have added some words to the README. No time to do more today.
