### ISSUE TITLE
npm.py throwing error claiming nodejs/npm is not installed

### ISSUE THREAD

**Issue by gmisiurny** [abilian/flask-vite#2]
* Flask-Tailwind version: 0.2.1
* Python version: 3.11.1
* Operating System: Windows 11
* node v18.13.0
* npm v8.19.3

### Description

Starting a new Flask project with the following tree: 

```
│   app.py
│           
├───static
├───templates
├───vite
│   │   .gitignore
│   │   bs.config.js
│   │   package.json
│   │   postcss.config.js
│   │   tailwind.config.js
│   │   
│   └───src
│           styles.css
│           
└───__pycache__
        app.cpython-311.pyc
```

`flask vite init` worked but every time I try `flask vite install` or `flask vite start` command, I get the following error : 
```
It looks like node.js and/or npm is not installed or cannot be found. Visit https://nodejs.org to download and install node.js for your system.
```

![2023-01-15 225638](https://user-images.githubusercontent.com/48993201/212676043-94da415c-04f5-4025-b865-db788255a887.png)

### What I Did

```
flask vite init
flask vite install
flask vite start
```

**Comment by PallavMarwaha** [comment]
Hi, did you manage to make it work?

**Comment by msimoni18** [comment]
I also get `flask_vite.npm.NPMError` when trying to run `flask vite install` or `flask vite start` in a newly create `vite` project that I created using `npm create vite@latest`. Any thoughts on why this error is occurring?

**Comment by gmisiurny** [comment]
Sorry for the late answer, no I never found out what was going on...

**Comment by TaniKyuun** [comment]
# Work around

- Windows 11 22H2
- flask-vite 0.3.0
- Python 3.11.5
- node v20.6.1
- npm 9.8.1

**Description**

Installed flask-vite under a virtual environment. using the following command:

```bash
phyton -m venv .venv
```

Then I activated the virtual environment and installed flask-vite using the following command:

```bash
.\.venv\Scripts\activate

pip install flask-vite
```

Then under the virtual environment folder `.venv` GOTO `Lib\site-packages\flask_vite` and edit the file `npm.py` and change the line:

```python
NPM_BIN_PATH = "npm"

# to

NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"
# or wherever your npm.cmd is located
```

alternative method

```python
#From this
import subprocess
from dataclasses import dataclass
from textwrap import dedent

# Assume npm is in the path for now.
NPM_BIN_PATH = "npm"

class NPMError(Exception):
    pass
.........

#To this
import subprocess
from dataclasses import dataclass
from textwrap import dedent
import shutil

NPM_BIN_PATH = shutil.which("npm")


class NPMError(Exception):
    pass
.........
```

**Comment by sfermigier** [comment]
I've made a new release where the error message is more explicit, and the NPM_BIN_PATH is configurable (via Flask config).
