### ISSUE TITLE
Is there a sample showing how to use this plugin for injecting js code in flask frontend?

### ISSUE THREAD

**Issue by ibrahoss** [abilian/flask-vite#4]
* Flask-Tailwind version:  3.0.0
* Python version: 3.10
* Operating System: ubuntu

### Description

I have a flask web app where I also have a javascript frontend using ES6 modules which I import directly in my HTML templates. 
I thought of using flask-vite to manage javascript app in node environment and serve the javascript using vite. 
My issues: 
1) I initiated added flask-vite as instructed. I then ran the commands to init, install, and build using "flask vite ...". Then when I run my flask server, I get the following error in browser: Failed to load resource: net::ERR_CONNECTION_REFUSED

2) I added my javascript source code with entry "main.js" inside the src folder. 
Now I am not sure how to get that injected in my HTML. So, I guessed I'd just add "`<div id="app"></div>`" in my HTML. Note that I want the javascript injected only when a specific HTML is loaded. My front end does not work. Do I need to add a vite.config.js?

**Comment by aie007** [comment]
same issue. Unable to understand how to use this plugin...
